language: node_js

node_js:
- '12.16.2'
cache: 
directories:
- node_modules
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database your_database_name;' -U postgres
script:
- npm run test
notifications:
  email: false